global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'spring-boot-producer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['aws-tester:8000']
    basic_auth:
      username: 'adminmaster'
      password: '/run/secrets/admin_password'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']