management:
  endpoints:
    web:
      base-path: ${ACTUATOR:/actuator}
      exposure:
        include: "*"
    access:
      default: read-only
  endpoint:
    info:
      access: read-only
    health:
      show-details: always
    metrics:
      access: read-only 
    prometheus:
      access: unrestricted 

  tracing:
    enabled: true
    sampling:
      probability: 1.0

  prometheus:
    metrics:
      export:
        enabled: true

tracing:
  url: ${JAEGER_URL}